# Generated by Django 4.2.3 on 2023-08-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0004_alter_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
